language: android
jdk:
  - oraclejdk8
#  - openjdk7

android:
    components:
        - tools
        - build-tools-24.0.3
        - android-24
        - android-23
        - extra-android-m2repository
    licences:
        - '.+'

before_install:
  - git submodule update --init
script:
    - ./gradlew assembleDebug assembleDebugAndroidTest
