language: android
android:
    components:
        - build-tools-24.0.3
        - android-24
        - extra-android-support
        - extra-android-m2repository
    licences:
        - '.+'
script:
    - ./gradlew assembleDebug assembleDebugAndroidTest
