language: android
jdk:
  - oraclejdk8
  - openjdk8

android:
    components:
        - tools
        - build-tools-24.0.3
        - android-24
        - android-23
        - extra-android-support
        - extra-android-m2repository
    licences:
        - '.+'
script:
    - ./gradlew assembleDebug assembleDebugAndroidTest
