language: android
android:
    components:
        - build-tools-19.1.0
        - android-10
        - extra-android-support
    licences:
        - '.+'
before_script:
    - android update project -t android-10 -p .
    - android update lib-project -p libsrc/pulltorefresh 
    - mkdir libs
    - cp -r /usr/local/android-sdk/extras/android/support/v4/android-support-v4.jar libs/
script:
    - ant debug lint

