language: android
jdk:
  - oraclejdk8
#  - openjdk7

android:
    components:
        - tools
        - build-tools-24.0.3
        - android-24
        - android-23
        - extra-android-m2repository
    licences:
        - '.+'

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive  
script:  
  - ./gradlew assembleDebug assembleDebugAndroidTest
